server:
  port: 9000

spring:
  profiles:
    active: "dev"

---

spring:
  config:
    activate:
      on-profile: "dev"

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:webapp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: ALWAYS

---

spring:
  config:
    activate:
      on-profile: "prod"

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bank-account
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

