spring:
  profiles:
    active: "prod"

server:
  port: 8090

---

spring:
  config:
    activate:
      on-profile: "dev"

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:webapp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  sql:
    init:
      mode: ALWAYS

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://auth-server:9000

---

spring:
  config:
    activate:
      on-profile: "prod"

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/bankaccount?createDatabaseIfNotExist=true
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://auth-server:9000