name: Register container and deploy

on:
   push:
      paths: [backend/**, .github/workflows/backend_workflow.yml]
      paths-ignore: ['**.md', '**.MD']
      branches:
         - main 

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@main
        with:
         sparse-checkout: backend
         fetch-depth: 0
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
         login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
         username: ${{ secrets.REGISTRY_USERNAME }}
         password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
         docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/bank:latest \
            --build-arg CLIENT=${{ secrets.CLIENT }} --build-arg EMAIL=${{ secrets.EMAIL }} --build-arg PASSWORD="${{ secrets.EMAIL_PASSWORD }}" \
            --build-arg KEY=${{ secrets.JWT_KEY }} --build-arg ISSUER=${{ secrets.JWT_ISSUER }} --build-arg DB_URL=${{ secrets.DB_URL }} \
            --build-arg DB_NAME=${{ secrets.DB_NAME }} --build-arg DB_PASS=${{ secrets.DB_PASS }} backend/
            
         docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/bank:latest