name: Deploy to Chromatic

on:
   push:
      paths:
         - fronted/**
      branches:
         - main 
jobs:
   test_and_deploy:
      runs-on: ubuntu-22.04
      steps:
         - uses: actions/checkout@v4
         - uses: actions/setup-node@v4
           with:
            node-version: 18
            cache: 'npm'
         - run: cd fronted
         - name: Install dependencies
           run: npm ci
         - name: Test project
           run: npm run test
         - uses: chromaui/action@v1
           # Options required for Chromatic's GitHub Action
           with:
            #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/svelte/en/deploy/ to obtain it
            token: ${{ secrets.GITHUB_TOKEN }}
            projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
            exitZeroOnChanges: true