name: Deploy to Chromatic

on:
   push:
      paths:
         - fronted/**
         - .github/workflows/deploy_to_chromatic.yml
      branches:
         - main 
jobs:
   test_and_deploy:
      runs-on: ubuntu-22.04
      defaults:
         run:
            working-directory: fronted
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: fronted
            fetch-depth: 0
         - uses: actions/setup-node@v4
           with:
            node-version: 18
            cache: 'npm'
            cache-dependency-path: fronted/package-lock.json
         - name: Install dependencies
           run: npm ci
         - name: Test project
           run: npm run test
         - uses: chromaui/action@v1
           # Options required for Chromatic's GitHub Action
           with:
            #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/svelte/en/deploy/ to obtain it
            token: ${{ secrets.GITHUB_TOKEN }}
            projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
            exitZeroOnChanges: true
            workingDir: fronted